CREATE TABLE IF NOT EXISTS pairs (
    ID TEXT PRIMARY KEY NOT NULL,
    hugs INT DEFAULT 0,
    kills INT DEFAULT 0,
    kisses INT DEFAULT 0,
    slaps INT DEFAULT 0,
    bites INT DEFAULT 0,
    pats INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS economy (
    id TEXT PRIMARY KEY NOT NULL,
    gold FLOAT DEFAULT 0.00,
    dayclaim INT DEFAULT 0,
    streak INT DEFAULT 0,
    maxbal FLOAT DEFAULT 50.00,
    interest FLOAT DEFAULT 1.01,
    bankbal FLOAT DEFAULT 0.00
);